## Solutions

### Exercise 1

Create a vector of 10 integers. Expontiate each element to the power of 3.

In [1]:
x = collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [2]:
x .^3

10-element Vector{Int64}:
    1
    8
   27
   64
  125
  216
  343
  512
  729
 1000

### Exercise 2

Create a matrix `X` that has 4 rows and 3 columns populated by floats. Create a second matrix `Y` that contains the square roots of `X`.

In [3]:
X = reshape(collect(rand(12)), (4,3))

4×3 Matrix{Float64}:
 0.705256  0.450657  0.0512176
 0.611181  0.906951  0.654661
 0.138953  0.401237  0.0390053
 0.963232  0.237221  0.30242

In [4]:
Y = sqrt.(X)

4×3 Matrix{Float64}:
 0.839795  0.67131   0.226313
 0.78178   0.95234   0.809111
 0.372764  0.633433  0.197498
 0.981444  0.487054  0.549928

### Exercise 3

Using matrix `X` from exercise 2 estimate the geometric mean of each column and each row separately.

In [5]:
using StatsBase

In [6]:
map(geomean, eachcol(X))

3-element Vector{Float64}:
 0.49009347665630226
 0.44411561100307123
 0.14102386673465284

In [7]:
[geomean(col) for col in eachcol(X)]

3-element Vector{Float64}:
 0.49009347665630226
 0.44411561100307123
 0.14102386673465284

In [8]:
map(geomean, eachrow(X))

4-element Vector{Float64}:
 0.2534373439505832
 0.7132742317674823
 0.12955803974175414
 0.41036022685394014

In [9]:
[geomean(row) for row in eachrow(X)]

4-element Vector{Float64}:
 0.2534373439505832
 0.7132742317674823
 0.12955803974175414
 0.41036022685394014

### Exercise 4

Write a function that takes as arguments a matrix and a vector and estimates the R_square also know as coefficient of determination. The R_square is a very common metric when fitting a linear model providing an indication as to how well the recorded variable(s) or features that we have information about can explain the variance of a variable we are interested in gaining insights about e.g. for prediction purposes.  R_square is estimated by subtracting from 1 the ratio of the sums of squares of the residuals divided by the total sums of squares (https://en.wikipedia.org/wiki/Coefficient_of_determination). In the fucntion we can consider the vector as the response variable and the matrix containing the features. Keep in mind that the coefficient of determination has a lot of limitations and generally limited value in practical applications, but that is more of a topic for a statistics course. 

In [10]:
function R²(X, y)
    model = X \ y
    fitted = X * model
    residual = y - fitted
    SS_resid = sum(e -> e^2, residual)
    SS_total = sum(v -> (v - mean(y))^2, y)
    return 1 - SS_resid/SS_total
end

R² (generic function with 1 method)

In [11]:
X = [ones(15) rand(15)]

15×2 Matrix{Float64}:
 1.0  0.0404694
 1.0  0.500134
 1.0  0.844625
 1.0  0.962036
 1.0  0.945167
 1.0  0.356147
 1.0  0.054621
 1.0  0.38204
 1.0  0.462078
 1.0  0.411813
 1.0  0.0250251
 1.0  0.366543
 1.0  0.842772
 1.0  0.808567
 1.0  0.857428

In [12]:
y = X[:,2] - collect(rand(15))

15-element Vector{Float64}:
 -0.8954224248047824
  0.16786597177578633
  0.8382538283345395
  0.6617994969701151
  0.5566277959348906
  0.11142816570923975
 -0.4676339398105279
 -0.5646511608250077
  0.14064642074802292
 -0.5788567547057154
 -0.4777816463258583
  0.23969718384780303
  0.6727817748689995
 -0.09966983691382303
  0.7136693216808828

In [13]:
using Statistics

In [14]:
cor(y,X[:,2])

0.8363727729037836

In [15]:
R²(X,y)

0.6995194152547641